# Generated by Django 4.2.1 on 2023-05-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Salary'),
        ),
    ]
